---
- name: "Configure Loopback"
  cli_config:
    config: "{{ lookup('template', 'loopback_template.j2') }}"
  with_items:
    - { name: 'Loopback127', subnet: '192.168.127.0/24' }
    - { name: 'Loopback128', subnet: '192.168.128.0/24' }
