---
- name: "Hubbell Playbook"
  hosts: all
  connection: network_cli

  tasks:
  - name: "Backup existing config"
    ios_config:
      backup: "yes"
      backup_options:
        filename: "{{ inventory_hostname }}.txt"


  - name: "Create output directory"
    file:
      path: "outputs"
      state: directory
    run_once: true

  - name: "Fetch ASN number and save"
    block:
      - name: "Get ASN"
        set_fact: 
          my_var: "{{ lookup('file','{{ item }}') | regex_search('router bgp (.+)', '\\1') }}"
        loop: "{{ lookup('file', 'backup/*.txt') }}"
      - name: "Save ASN"
        lineinfile:
          path: outputs/ASN.txt
          line: "{{ inventory_hostname }} : {{ my_var }}"
    ignore_errors: yes
