---
- name: "Playbook on routers"
  hosts: hubbell,aryaka,mpls,cloud
  connection: network_cli

  tasks:
  - name: "Backup existing config"
    ios_config:
      backup: "yes"
      backup_options:
        filename: "{{ inventory_hostname }}.txt"


  - name: "Create output directory"
    file:
      path: "outputs"
      state: directory
    run_once: true

  - name: "Create ASN file"
    file:
      path: "outputs/BGP_ASN_INFO.txt"
      state: touch
    run_once: true

  - name: "Fetch ASN and save"
    block:
      - name: "Get BGP running config"
        cli_command:
          command: "show run | section router bgp"
        register: asn
 
      - name: "Grep ASN number"
        set_fact: 
          my_var: "{{ asn.stdout_lines[0] | regex_search('router bgp (.+)', '\\1') }}"

      - name: "Save ASN"
        lineinfile:
          path: outputs/BGP_ASN_INFO.txt
          line: "{{ inventory_hostname }} : {{ my_var[0] }}"   
    when: ansible_network_os == 'ios'
   
  - name: "Configure SNMP"
    cli_config: 
      config: "{{ lookup('template', 'snmp_template.j2') }}"
  
  - name: "Configure loopback”
    ansible.netcommon.cli_config:  
      command:
        - interface {{item.name}}
        - ip address {{ item.subnet | ipaddr(random(1,254)) }} 255.255.255.255
        - no shutdown
      with items:
        - { name: ‘Loopback127’, subnet:’192.168.127.0/24’ }
        - { name: ‘Loopback128’, subnet:’192.168.128.0/24’ }

- name: "Changes on firewall"
  hosts: firewall

  tasks:
  - name: "Enable node-exporter on firewall"
    ansible.builtin.shell:
      cmd: ./node_exporter &
      chdir: node_exporter-1.1.2.linux-amd64/
     
