---
- name: "Hubbell Playbook"
  hosts: all
  connection: network_cli

  tasks:
  - name: "Backup existing config"
    ios_config:
      backup: "yes"
      backup_options:
        filename: "{{ inventory_hostname }}.txt"


  - name: "Create output directory"
    file:
      path: "outputs"
      state: directory
    run_once: true

  - name: "Create ASN file"
    file:
      path: "outputs/BGP_ASN_INFO.txt"
      state: touch
    run_once: true

  - name: "Fetch ASN and save"
    block:
      - name: "Get BGP running config"
        cli_command:
          command: "show run | section router bgp"
        register: asn
 
      - name: "Grep ASN number"
        set_fact: 
          my_var: "{{ asn.stdout_lines[0] | regex_search('router bgp (.+)', '\\1') }}"

      - name: "Save ASN"
        lineinfile:
          path: outputs/BGP_ASN_INFO.txt
          line: "{{ inventory_hostname }} : {{ my_var[0] }}"      
