---
- name: "Hubbell Playbook"
  hosts: all
  connection: network_cli

  tasks:
  - name: "Backup existing config"
    ios_config:
      backup: "yes"
        backup_options:
          filename: "{{ inventory_hostname }}"


